# This is a basic workflow to help you get started with Actions

name: CI_CD

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      -     uses: actions/checkout@v2
            with:
                clean: true

      # Runs a single command using the runners shell
      -     name: Run a one-line script
            shell: cmd
            run: echo Hello, world!

      # Runs a set of commands using the runners shell
      -     name: Run a multi-line script
            shell: cmd
            run: |
              echo Add other actions to build,
              echo test, and deploy your project.
          
  deploy:
   
    runs-on: self-hosted
    
    steps:
        -   name: Create a file
            shell: cmd
            run: |
                mkdir deployFolder
                cd deployFolder
                echo > testfile.txt
            
        -   name: Save artifact
            uses: actions/upload-artifact@v2
            with:
                name: test-artifact
                path: $GITHUB_WORKSPACE/deployFolder/*
